### ISSUE TITLE
family_doctor check

### ISSUE THREAD

**Issue by mrgallagher** [391DatabaseGroup/RadiologyInformationSystem#23]
we need to enforce the constraint that 
a) the doctor and patient exist in users
b) that the doctor id entered is of class d
c) that the patient id entered is of class p

im not sure if we want to do this in management module when they are created or if it should be a constraint on the database.

**Comment by IDrinkTooMuchCoffee** [comment]
family_doctor and users both have foreign key constraints on the ids, so if somebody tries to insert a row where those ids do not exist in the persons table, there will be an exception. Perhaps the thing to do is catch such an exception and prompt the user to either create the rows in the persons table or  abandon the transaction?

**Comment by mrgallagher** [comment]
This works now. user management checks for if the doctor or patient id's entered are in fact doctors and patients respectively. everything else is handled by the database
