### ISSUE TITLE
ID generator

### ISSUE THREAD

**Issue by LjNick** [391DatabaseGroup/RadiologyInformationSystem#5]
Need a component that will generate unique ids for entries in the database

**Comment by IDrinkTooMuchCoffee** [comment]
Id generator is up on main branch in com folder now. Should work good for generating any new unique ID numbers when inserting a row or whatever.

**Comment by LjNick** [comment]
Are you done with this issue?

**Comment by IDrinkTooMuchCoffee** [comment]
I believe so.

**Comment by IDrinkTooMuchCoffee** [comment]
Modified to extend BaseLayer. All code requesting a unique ID should call generate inside a try block now.
